routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('sw0102638', 'Sw0102638Controller');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/sw0102638.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class sw0102638 extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Sw0102638Controller.php
<?php

namespace App\Http\Controllers;

use App\sw0102638;
use Illuminate\Http\Request;

class Sw0102638Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $student = sw0102638::all();

        return view('index',compact('student'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
         $validatedData = $request->validate([
            'year' => 'numeric|required|max:2025|min:2018',
            'sem' => 'numeric|required',
            'cgpa' => 'numeric|required|between:0.00,4.00',
        ]);

        $student = new sw0102638;
        $student->name = $request->input('name');
        $student->year = $request->input('year');
        $student->semester = $request->input('sem');
        $student->cgpa = $request->input('cgpa');
        $student->save();

        return redirect()->route('sw0102638.index')->with('success_message', 'Data successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\sw0102638  $sw0102638
     * @return \Illuminate\Http\Response
     */
    public function show(sw0102638 $sw0102638)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\sw0102638  $sw0102638
     * @return \Illuminate\Http\Response
     */
    public function edit(sw0102638 $sw0102638)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\sw0102638  $sw0102638
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, sw0102638 $sw0102638)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\sw0102638  $sw0102638
     * @return \Illuminate\Http\Response
     */
    public function destroy(sw0102638 $sw0102638)
    {
        //
    }
}

resources/views/create.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Add new data</title>
</head>
<body>
	@if ($errors->any())
      <div class="alert alert-danger" style="color: red">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
	@endif

	<form method="post" action="{{route('sw0102638.store')}}">
		@csrf
		Name : <input type="text" name="name"><br>
		Year : <input type="integer" name="year"><br>
		Semester : <input type="integer" name="sem"><br>
		CGPA : <input type="double" name="cgpa"><br>
		<br>
		<input type="submit" value="submit">
	</form>
</body>
</html>

resources/views/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Homepage</title>
</head>
<body>
	@if(session()->has('success_message'))
        	<p style="color:green;">{{ session()->get('success_message') }}</p>
	@endif
	<table border="1" cellpadding="10">
	  	<tr>
		    <th>Name</th>
		    <th>Year</th> 
		    <th>Semester</th>
		    <th>CGPA</th>
	  	</tr>
	  	@foreach($student as $s)
		<tr>
			    <td>{{$s->name}}</td>
			    <td>{{$s->year}}</td> 
			    <td>{{$s->semester}}</td>
			    <td>{{$s->CGPA}}</td>
		</tr>
		@endforeach	
	</table>
	<br><br>
	<button onclick="goTo()">Add new record</button>

	<script type="text/javascript">
		function goTo() {
			window.location = "{{route('sw0102638.create')}}";
		}
	</script>
</body>
</html>